import pandas as pd
import numpy as np
df = pd.read_excel("excel-comp-data.xlsx")
print(df)
print("Index",df.index)
print("Columns",df.columns)
print("*************************Filter for Jan > 70k ******************************")
print(df[df.Jan <= 70000])
print("***********************************Setting a Index*********************")
df.set_index('name',inplace = True)
print(df)
print("***********************************SORTING An Index*********************")
print(df.sort_index())
print("*****************************Find the city for Name index Bauch-Goldner***********************************")
print("Col read",df.loc['Bauch-Goldner','city'])
print("****************************************Creating a number Index on Current Index************************************************")
df.reset_index( "name",inplace = True)
print(df)
